index:
    path: /pizza/list
    defaults: { _controller: PizzaBundle:Pizza:pizzaList }

create_pizza:
    path: /pizza/create
    defaults: { _controller: PizzaBundle:Pizza:createPizza }

edit_pizza:
    path: /pizza/edit/{id}
    defaults: { _controller: PizzaBundle:Pizza:editPizza }