root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /pizza/list
        permanent: true

pizza_list:
    path: /pizza/list
    defaults: { _controller: PizzaBundle:Pizza:pizzaList }

create_pizza:
    path: /pizza/create
    defaults: { _controller: PizzaBundle:Pizza:createPizza }

edit_pizza:
    path: /pizza/edit/{id}
    defaults: { _controller: PizzaBundle:Pizza:editPizza }

ingredient_list:
    path: /ingredient/list
    defaults: { _controller: PizzaBundle:Ingredient:ingredientList }

create_ingredient:
    path: /ingredient/create
    defaults: { _controller: PizzaBundle:Ingredient:createIngredient }

edit_ingredient:
    path: /ingredient/edit/{id}
    defaults: { _controller: PizzaBundle:Ingredient:editIngredient }